### ISSUE TITLE
HTML #anchors are lost when redirecting and admin is logged in

### ISSUE THREAD

**Issue by Saxtus** [dgw/yourls-dont-track-admins#2]
When storing URLs with an HTML anchor name, they appear correctly in the database, but when the short URL is used when the plugin is enabled and admin is logged in, their anchor disappear and never used.

What steps will reproduce the problem?
1. Add a URL that has an anchor, for example: http://justgetflux.com/faq.html#comment-982376025
2. Check the admin interface to see that it is stored correctly as http://justgetflux.com/faq.html#comment-982376025
3. Use the shortlink to jump to the target page while plugin is enabled and admin is logged in
4. The target page is stripped from it's anchor and appears as: http://justgetflux.com/faq.html

Using: YOURLS v1.6, PHP v5.3.22, Chrome v28.0.1500.95 m

**Comment by dgw** [comment]
No response for almost 2 years, and appears to be a YOURLS issue. Also occurs with this plugin deactivated on my instance. Closing.
